// Code generated by mockery v2.10.0. DO NOT EDIT.

package checker

import (
	product "github.com/andrysds/colly-example/product"
	mock "github.com/stretchr/testify/mock"
)

// MockPartner is an autogenerated mock type for the Partner type
type MockPartner struct {
	mock.Mock
}

// GetProduct provides a mock function with given fields: slug
func (_m *MockPartner) GetProduct(slug string) (*product.Product, error) {
	ret := _m.Called(slug)

	var r0 *product.Product
	if rf, ok := ret.Get(0).(func(string) *product.Product); ok {
		r0 = rf(slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields:
func (_m *MockPartner) Login() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
